version: "3.9"

services:
  db_dev:
    image: postgres:16
    profiles: ["dev"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db_dev
    ports:
      - "5440:5432"
    volumes:
      - auth_service_dev_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_prod:
    image: postgres:16
    profiles: ["prod"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db_prod
    expose:
      - "5432"
    volumes:
      - auth_service_prod_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db_prod"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prod_net

  auth_dev:
    build: .
    image: auth-service:dev
    profiles: ["dev"]
    depends_on:
      db_dev:
        condition: service_healthy
    env_file:
      - .env.dev
    environment:
      DATABASE_URL: postgresql://postgres:password@db_dev:5432/auth_db_dev
      APP_BASE_URL: http://localhost:8050
    ports:
      - "8050:8050"
    command: >
      bash -c "python scripts/create_db.py && alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8050 --root-path /auth"

  auth_prod:
    build: .
    image: auth-service:prod
    profiles: ["prod"]
    depends_on:
      db_prod:
        condition: service_healthy
    env_file:
      - .env.prod
    environment:
      DATABASE_URL: postgresql://postgres:password@db_prod:5432/auth_db_prod
      APP_BASE_URL: http://localhost:8050
    expose:
      - "8050"
    command: >
      bash -c "python scripts/create_db.py && alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8050 --root-path /auth"
    networks:
      - prod_net

volumes:
  auth_service_dev_db:
  auth_service_prod_db:

networks:
  prod_net:
    external: true
    name: prod_net
